@Company.Ordering.API_HostAddress = http://localhost:5186

GET {{Company.Ordering.API_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Company.Ordering.API_HostAddress}}/Orders
Content-Type: application/json

{
  "customerName": "John Doe",
  "orderDate": "2025-05-10T00:00:00Z",
  "invoiceAddress": "123 Main St, Springfield, USA",
  "invoiceEmailAddress": "johndoe@example.com",
  "invoiceCreditCardNumber": "4111111111111111",
  "products": [
    {
      "productId": 12345,
      "name": "Product A",
      "quantity": 2,
      "price": 19.99
    }
  ]
}
###
GET {{Company.Ordering.API_HostAddress}}/Orders/abc